// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20240205142051_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "T-shirt",
                            Description = "Description",
                            ImageURL = "https://github.com/Bethania-Freitas/erudio-microsservices/blob/main/ShoppingImages/11_mars.jpg",
                            Name = "Camiseta_OccupeMars",
                            Price = "69,9"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Tools",
                            Description = "Description",
                            ImageURL = "https://github.com/Bethania-Freitas/erudio-microsservices/blob/main/ShoppingImages/10_milennium_falcon.jpg?raw=true",
                            Name = "Millenium Falcom",
                            Price = "469,9"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "T-shirt",
                            Description = "Description",
                            ImageURL = "https://github.com/Bethania-Freitas/erudio-microsservices/blob/main/ShoppingImages/12_gnu_linux.jpg?raw=true",
                            Name = "Camiseta Gnu Linux",
                            Price = "69,9"
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "T-shirt",
                            Description = "Description",
                            ImageURL = "https://github.com/Bethania-Freitas/erudio-microsservices/blob/main/ShoppingImages/13_dragon_ball.jpg?raw=true",
                            Name = "Camiseta Dragon Ball",
                            Price = "59,9"
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Tools",
                            Description = "Description",
                            ImageURL = "https://github.com/Bethania-Freitas/erudio-microsservices/blob/main/ShoppingImages/14_patch_nasa.jpg?raw=true",
                            Name = "Patch Nasa",
                            Price = "29,9"
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Tools",
                            Description = "Description",
                            ImageURL = "https://github.com/Bethania-Freitas/erudio-microsservices/blob/main/ShoppingImages/1_super_mario.jpg?raw=true",
                            Name = "Caneca Mario",
                            Price = "29,9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
